### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by YYT1002** [hhcho/densvis#7]
I met a ZeroDivisionError. It is very confusing. 

Traceback (most recent call last):

  File "/Users/uqyyao4/Documents/Project/03_GNN_for_visualization/code/densvis-master/densmap/trial_densmap.py", line 17, in <module>
    emb, ro, re = densmap.densMAP(verbose=True, n_components=2,

  File "/Users/uqyyao4/Documents/Project/03_GNN_for_visualization/code/densvis-master/densmap/densmap/densmap_.py", line 2086, in fit_transform
    self.fit(X, y)

  File "/Users/uqyyao4/Documents/Project/03_GNN_for_visualization/code/densvis-master/densmap/densmap/densmap_.py", line 1967, in fit
    self.embedding_ = simplicial_set_embedding(

  File "/Users/uqyyao4/Documents/Project/03_GNN_for_visualization/code/densvis-master/densmap/densmap/densmap_.py", line 1295, in simplicial_set_embedding
    embedding = optimize_layout(

ZeroDivisionError: division by zero

**Comment by anashwin** [comment]
I think this might be a compatibility issue with the most recent version of the `numba` library. Can you see what version you have? The code should work with `numba` version 0.48.0.

**Comment by YYT1002** [comment]
> I think this might be a compatibility issue with the most recent version of the `numba` library. Can you see what version you have? The code should work with `numba` version 0.48.0.

The numba version is 0.48.0
It could be the 'numba' problem. I changed 
> @numba.njit(fastmath=True, parallel=**True**)
> def optimize_layout
 to 
> @numba.njit(fastmath=True, parallel=False)
> def optimize_layout
Then the problem solved. But I gusee the consequence may be more running time cost.

**Comment by FischerJoBio** [comment]
I get the same error when using R reticulate to run the code. Unfortunately, I cannot install numba version 0.48.0 due to incompatibilities with the M1 chip (I get an error similar to the open issue https://github.com/hhcho/densvis/issues/13 when trying to instal with numba 0.48.0), but have to use a newer version. Any ideas on how to get around this error while using a newer numba?
